name: Create GitHub Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to release'
                required: true
                type: string
            previous_version:
                description: 'Previous version to compare with'
                required: true
                type: string

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Create Release
                uses: softprops/action-gh-release@v1
                with:
                    tag_name: v${{ github.event.inputs.version }}
                    name: v${{ github.event.inputs.version }}
                    body: |
                        ## What's Changed
                        
                        Check the [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
                        
                        ## Maven
                        ```xml
                        <dependency>
                            <groupId>io.github.mihaistreames</groupId>
                            <artifactId>afe</artifactId>
                            <version>${{ github.event.inputs.version }}</version>
                        </dependency>
                        ```
                        
                        **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ github.event.inputs.previous_version }}...v${{ github.event.inputs.version }}
                    draft: false
                    prerelease: false