name: Publish Python Package to PyPI

on:
    release:
        types: [created]

jobs:
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment: release
        permissions:
            # This permission is needed for private repositories.
            contents: read
            # This permission is required to publish to PyPI.
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build

            - name: Build package
                # This command assumes your setup.py is in the Python/ subdirectory
              run: |
                  cd Python
                  python -m build

            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  # The packages are located in the Python/dist/ directory
                  packages_dir: Python/dist/